#!/usr/bin/env bash
# Script to display information about subdomains

# Functions to display DNS Record Information
get_dns_info() {
    domain="$1"
    subdomain="$2"
    record_type=$(dig +short "$subdomain.$domain" | awk '{print $4}')
    destination=$(dig +short "$subdomain.$domain" | awk 'print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main Script
domain="$1"
subdomain="$2"

## Check if domain argument is provided
if [ -z "$domain" ]
then
    echo "Error: Domain argument is mandatory"
    exit 1
fi

## Check if subdomain argument is provided
if [ -z "$subdomain" ]
then
    # Display Information for default subdomains
    get_dns_info "$domain" "www"
    get_dns_info "$domain" "lb-01"
    get_dns_info "$domain" "web-01"
    get_dns_info "$domain" "web-02"
else
    # Display Information for specified subdomain
    get_dns_info "$domain" "$subdomain"
fi