#!/usr/bin/env bash
# Script to display information about subdomains

# Functions to display DNS Record Information
get_dns_info() {
    domain="$1"
    subdomain="$2"
    record_type=$(dig "$subdomain.$domain" +noall +answer | awk '{print $4}')
    destination=$(dig +short "$subdomain.$domain")
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main Script
domain="$1"
subdomain="$2"

## Check if args is atleast one or more
if [ "$#" -lt 1 ]
then
    echo "Error: Domain argument is mandatory"
    exit 1
## Check if both args are provided, then display info for only that subdomain
elif [ "$#" -eq 2 ]
then
    get_dns_info "$domain" "$subdomain"
## Check if only arg1 (domain) is passed
elif [ "$#" -eq 1 ]
then
    ### Created an array of subdomains to loop over
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"
    do
        get_dns_info "$domain" "$subdomain"
    done
fi
