#!/usr/bin/env bash
# script that transfers a file from our client to a server
LOCAL_FILE=$1
SERVER=$2
UNAME=$3
KEY=$4

# Check Number of Args
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -o StrictHostKeyChecking=no -i "$KEY" "$LOCAL_FILE" "$UNAME"@"$SERVER":~/