#!/usr/bin/env bash
# This script creates a backup of all the databases

# Variables
ar_name="$(date +%d-%m-%Y).tar.gz"
backup="backup.sql"
password=$1

# Check No. of args
if [ $# -lt 1 ]; then
    echo "Usage: $0 <password>"
    exit 1
else
    # Dump
    echo "Creating dump"
    sudo mysqldump -u root -p "$password" --all-databases | sudo tee "$backup" > /dev/null
    if [ $? -eq 0 ]; then
        echo "Dump Created Successfully"
    else
        echo "Error creating dump."
        exit 1
    fi

    # Archive
    echo "Compressing into tar.gz"
    tar -czvf "$ar_name" "$backup"
    if [ $? -eq 0 ]; then
        echo "Archive created successfully: $ar_name"
    else
        echo "Error creating archive"
        exit 1
    fi
fi