#!/usr/bin/env bash
# A script that prints bad luck at number 4 and goodluck at number 8 
valid=true
counter=1
while [ $valid ]
do
    if [ $counter -eq 4 ];
    then
        echo "bad luck"
    elif [ $counter -eq 8 ];
    then
        echo "good luck"
    elif [ $counter -eq 11 ];
    then
        break
    else :
        echo "Best School"
    fi
((counter++))
done