#!/usr/bin/env bash
# To file or not to file

pwd="$(pwd)"
ls="$(ls "$pwd")"
name_of_file="school"

for filename in $ls
do
    if [ "$filename" == "$name_of_file" ]
    then
        checkfile="$name_of_file"
    fi
done       

if [ -e "$checkfile" ]
then
    echo "$checkfile file exists"
    if [ -s "$checkfile" ]
    then
        echo "$checkfile file is not empty"
    else :
        echo "$checkfile file is empty"
    fi
    if [ -f "$checkfile" ]
    then
        echo "$checkfile is a regular file"
    fi
else :
    echo "$name_of_file file does not exist"
fi