#!/usr/bin/env bash
# This script configures the container to run nginx as the nginx user
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo sed -i.bak '/^server {/,/^}/ s/80/8080/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx stop
sudo -u nginx service nginx start