#!/usr/bin/env bash
# This script configures the container to run nginx as the nginx user

# Change ownership of the /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf

# Change permissions to allow rwx for nginx root user
sudo chmod 700 /etc/nginx/nginx.conf

# Change the listening port
sudo sed -i.bak '/^server {/,/^}/ s/80/8080/' /etc/nginx/sites-available/default

# For this specific box, I found that apache2 was listening on port 8080 which made
# it impossible for nignx to bind that port, so I had to kill it manually
pkill apache2

# Run the command
sudo -u nginx service nginx stop
sudo -u nginx service nginx start
